### ISSUE TITLE
Handle multiple sort properties in memory store. See todo

### ISSUE THREAD

**Issue by serby** [serby/save#4]

**Comment by vpArth** [comment]
This code:
```js
if (Array.isArray(options.sort)) {
  key = options.sort[0][0]
}
```

sets `key` to `'time'[0]` which is `'t'`, and then tries sort by undefined field `t`.

You can use `{sort: [['time', 'desc']]}` with current code or wait while it will be fixed...

Anyway this memory storage too temporary, it can't be used in real life, because we need restart workers sometimes, and it even not shares memory between workers in `node-cluster` scope.

ps: why `sort` key used instead of documented `$sort` ?

**Comment by serby** [comment]
The memory engine is only intended for single process apps, but more often for testing purposes.

I'm planing to over haul with this implementation: https://www.npmjs.com/package/sift which should solved a lot of the problems.

**Comment by serby** [comment]
Now supported.
